# Site settings
title: Kevin Puorro - Data Scientist & Sports Analytics Professional
description: Data Analyst specializing in sports analytics, statistical modeling, and business intelligence. Experience with Power BI, Python, and serving 100+ college football programs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kevin-puorro.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kevin Puorro
user_description: I'm a data scientist and analyst in Pittsburgh, Pennsylvania, originally from San Jose, California. I earned my Bachelor's in Statistics from Baylor University and am currently finishing my Master's in Data Science at Pitt. I'm currently working as a Data Analyst at Championship Analytics, serving 100+ college football programs nationwide. I'm passionate about sports analytics, business analytics, and using data to help organizations make smarter decisions. I'm always open to new opportunities and collaborations with any who are interested.
user_title: Data Analyst
email: kevin.puorro@hotmail.com
linkedin_username: kevin-puorro-b765b9263
# github_username: kevin-puorro

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
